### ISSUE TITLE
Copyright ??

### ISSUE THREAD

**Issue by brianteeman** [microsoft/clarity-joomla-plugin#1]
Is this code really copyright PB Web Development or did you just copy the google analytics plugin from https://nicheextensions.com/contact/

https://github.com/microsoft/clarity-joomla-plugin/blob/ba170542ed24a635475bb84d99b0abaf5de43db4/clarity.xml#L6

**Comment by ClaritySupport** [comment]
@brianteeman , Thanks for using Clarity. This issue is fixed.
