### ISSUE TITLE
Code not correct implemented

### ISSUE THREAD

**Issue by harrypotter06** [microsoft/clarity-joomla-plugin#4]
If you enable the pulugin, the code will not be correct implemented. The start for script-tag is missing, but i think

`<html>
<body>

<script>window.dataLayer = window.dataLayer \|\| [];dataLayer.push({'event': 'user_loggedin', 'user_id' : '290'});</script>function(c,l,a,r,i,t,y){
--
  | c[a]=c[a]\|\|function(){(c[a].q=c[a].q\|\|[]).push(arguments)};
  | t=l.createElement(r);t.async=1;t.src='//www.clarity.ms/tag/'+i+'?ref=joomla';
  | y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
  | })(window, document, 'clarity', 'script', 'xxxxxxxxxx');</script>

</body>
</html>`

**Comment by ClaritySupport** [comment]
@harrypotter06, Could you please ensure  that the code is correctly implemented and that the snippet is added and started automatically. Clarity starts collecting data as soon as the plugin is added and set up as mentioned [in the readme here](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fclarity-joomla-plugin&data=05%7C01%7Cv-vikasd%40microsoft.com%7Cd1994ea8650344bb394f08db0828010f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638112740198420115%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=S%2F6k7NGx7Guwvkg01GLCavXAQfJoea7ttRCqGNs8ZPU%3D&reserved=0). You can validate that Clarity is working by following [these steps](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fclarity%2Fsetup-and-installation%2Fclarity-setup%23verify-your-installation&data=05%7C01%7Cv-vikasd%40microsoft.com%7Cd1994ea8650344bb394f08db0828010f%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638112740198420115%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=w2O1Y3vl1tc54ADz0fF0P4z8e5ADQNQc7D7OeldYv3Y%3D&reserved=0). 
If this is not the case, then please share below details to assist you further.

•	Version of Joomla you are using? 
•	Your website URL
•	 Clarity project id?

**Comment by harrypotter06** [comment]
Hello,

after a half year, i got answer .....

It is the code that you plugin will enable if Plugin enabled.
That code are not correct and that can you check if you enable the plugin on your system end verrify if that the same that Microsoft had published

**Comment by ClaritySupport** [comment]
Hello,

It is the same as the one on the install manually part on Clarity dashboard. If this is not what you have, could you please share your website URL.


(function(c,l,a,r,i,t,y){
c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
t=l.createElement(r);t.async=1;t.src='//www.clarity.ms/tag/'+i+'?ref=joomla';
y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
})(window, document, 'clarity', 'script', 'xxxx');



Thanks,
Clarity Support Team
Visit our docs!: https://docs.microsoft.com/en-us/clarity<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fclarity&data=05%7C01%7Cv-vidasa%40microsoft.com%7C343fe08f40a94e184c6408da28fedd21%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637867372409365494%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Q1zklwmipOGmVmg01HjPFwTVAwft75whSRoB8fFF%2BoY%3D&reserved=0>
***@***.******@***.***>
***@***.***

Confidentiality note: This e-mail, and any attachment to it, contains privileged and confidential information intended only for the use of the individual(s) or entity named in the e-mail.  If the reader of the e-mail is not the intended recipient, or the employee or agent responsible for delivering it to the intended recipient, you are hereby notified that reading it is strictly prohibited.  If you have received this e-mail in error, please immediately return it to the sender and delete it from your system.

**Comment by harrypotter06** [comment]
No it isn't
What you open, you must be closed 

The issue in your code (if Plugin enabled):
<script type="text/javascript">function(c,l,a,r,i,t,y){
			c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
			t=l.createElement(r);t.async=1;t.src='//www.clarity.ms/tag/'+i+'?ref=joomla';
			y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
		})(window, document, 'clarity', 'script', 'bsk0medx2z');</script>

Do you see the problem? You forgot to put the brackets in front of the "function"!

Also technically undesirable "'?ref=joomla'" - It's nobody's business what is used for a system for a website. That has something to do with security.

Where can I "securely submit" my website, so how can I submit it without it being public here?

**Comment by ClaritySupport** [comment]
@harrypotter06 , Please share website address to our Clarity support alias at ClarityMS@microsoft.com

**Comment by harrypotter06** [comment]
Hello,

the new version fix the issue - Thanks for your support
