### ISSUE TITLE
Incompatibility with Joomla 4.2.6 or PHP 8.1

### ISSUE THREAD

**Issue by mostafaafrouzi** [microsoft/clarity-joomla-plugin#5]
After activating the plugin, the following error is displayed in all Joomla management sections:
```
An error has occurred.
0 Call to undefined method Joomla\CMS\Application\AdministratorApplication::isAdmin()

```
And in the user section of the site, the following error:
`Call to undefined method Joomla\CMS\Application\SiteApplication::isAdmin()
`
Joomla version: 4.2.6
PHP version: 8.1

**Comment by saghoneim** [comment]
Solved in v1.1.0.
